# Generated by Django 4.2.3 on 2023-07-27 18:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('otp_generated_time', models.DateTimeField(blank=True, null=True)),
                ('counter', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mmq_otp',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=50, verbose_name='User Type')),
            ],
            options={
                'db_table': 'mmq_usertype',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('mobile', models.CharField(max_length=15, unique=True, verbose_name='Mobile Number')),
                ('device_type', models.CharField(blank=True, choices=[(1, 'Website'), (2, 'IOS'), (3, 'Android')], max_length=50, verbose_name='Device Type')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified ')),
                ('email_verification_code', models.CharField(max_length=45, null=True, verbose_name='Email Verification')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Email')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='Password')),
                ('status', models.PositiveSmallIntegerField(default=1, verbose_name='Status: 1 for Active; 0 for InActive')),
                ('is_deleted', models.PositiveSmallIntegerField(default=0, verbose_name='Status: 1 for Deleted; 0 for Not Deleted')),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('activation_key', models.CharField(blank=True, max_length=40)),
                ('reset_password_key', models.CharField(max_length=40, null=True)),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='is verified ')),
                ('is_mobile_verified', models.BooleanField(default=False, verbose_name='is verified ')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('usertypes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('user_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usertype')),
            ],
            options={
                'db_table': 'mmq_user',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('dob', models.DateField(null=True, verbose_name='DOB')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='location')),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zip Code')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/profile_image/')),
                ('latitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='Longitude')),
                ('status', models.PositiveSmallIntegerField(default=1, verbose_name='Status: 1 for Active; 0 for InActive')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='users.user')),
            ],
            options={
                'db_table': 'mmq_profile',
            },
        ),
    ]
